spring.application.name=authservice
server.port=8081

# -------------------- Security --------------------
security.public.endpoints=/auth/login,/auth/register,/auth/refresh,/actuator/**

# -------------------- JWT --------------------
jwt.expiration=15m
jwt.refresh-expiration=1d

# -------------------- OpenAPI --------------------
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# -------------------- Actuator --------------------
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# -------------------- Database --------------------
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------- Liquibase --------------------
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# -------------------- JPA --------------------
spring.jpa.hibernate.ddl-auto=validate

# -------------------- Logging --------------------
logging.level.com.mymicroservice.authservice=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
